# -------
# Library
# -------

library:
  name: CacheFileProvider
  api: 21
  github: MFlisar/CacheFileProvider
  maven: io.github.mflisar.cachefileprovider
  maven-main-library: library
  multiplatform: false
  platforms:
    - android
  screenshots:  []
  branch: master
  demo: false

# ------------
# Dependencies
# ------------

dependencies:
  experimental: false

# ------------
# Groups
# ------------

groups: []

# ------------
# Modules
# ------------

modules:
  - name: library
    group: core
    description: This is a minimal library that offers a simple file provider (simple read only access for sharing files with other apps).
    optional: false
    platforms:
      - android
    platforms-info: ""
    dependencies: []